### ISSUE TITLE
cptStatusSheet_bas - undeclared variable

### ISSUE THREAD

**Issue by ryanbeard82** [AronGahagan/cpt-dev#167]
**Describe the bug**
Line 1422 - _lngHeader_ should be _lngHeaderRow_

**To Reproduce**
1. Open a schedule
2. Click the "Create Status Sheet" button in the cpt Ribbon Menu
3. click the "Create" button on the form

**Additional context**
Replacing the _lngHeader_ var with _lngHeaderRow_ on line 1422 resolves the issue

**Comment by AronGahagan** [comment]
Well, that's embarrassing. Thanks.
