### ISSUE TITLE
Cobra Export - Custom Output Directory

### ISSUE THREAD

**Issue by ryanbeard82** [AronGahagan/cpt-dev#387]
- [ ] Add GUI for mapping a custom output directory
- [ ] update file output to save to mapped custom directory
* if not mapped, use desktop default

**Comment by AronGahagan** [comment]
This might be helpful: https://github.com/AronGahagan/cpt-dev/blob/master/Core/cptBrowseFolder_bas.bas - retired it 4 years ago, but could resurrect it. Prompts the user for a directory path using the Windows API; takes one 'title' argument; returns the directory path.
