### ISSUE TITLE
cptCriticalPath_bas - handle blank lines

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#44]
## Problem
User reports: "In the Private Sub CleanCritFlag, it cannot handle a blank line in the IMS. I tested this in a dummy file and was able to replicate the results.  Might need to include a check for that earlier in the process, or an exception handling for it. If this Sub can't handle a blank line, then I'm guessing others within the module would balk at it also."

## Solution
Ignore blank lines with something like:
```visual-basic
If Task Is Nothing Then Goto next_task
```
Where `next_task` is an anchor prior to the `Next Task` statement of the For-Next loop.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch

**Comment by ryanbeard82** [comment]
Issue resolved - see Pull request #45
