### ISSUE TITLE
cptIMSCobraExport_bas - variables not defined

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#47]
## Problem
With the addition of Option Explicit, a few variables are popping up as undefined.

```visual-basic
2223: ACTarray(x).WP = w 'probably should be = WP, but could be duplicate of line 2216
2561: ACTarray(x).WP = w 'probably should be = WP, but could be duplicate of line 2554
4340: Set subProjs = curproj.Subprojects
4342: For Each subProj In subProjs
4346: Set curSProj = ActiveProject
4348: For Each t In curSProj.Tasks
```

## Solution
Define the variables (recommended) or remove Option Explicit (not recommended).

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch

**Comment by ryanbeard82** [comment]
Thanks Aron. Will tackle ASAP. Sorry for the troubles.

Respectfully,

Ryan Beard


[cid:8757CB1A-2705-47EE-9DF4-A6E33162E261@attlocal.net]


Tel: (256) 694-2745<tel:(256)%20694-2745>
Email: RyanBeard@ClearPlanConsulting.com<mailto:ryanbeard@clearplanconsulting.com>
Website: ClearPlanConsulting.com<http://www.clearplanconsulting.com/>


On Jun 24, 2019, at 11:33 AM, Aron Gahagan <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #47<https://github.com/AronGahagan/cpt-dev/issues/47> to @ryanbeard82<https://github.com/ryanbeard82>.

**Comment by AronGahagan** [comment]
Hey Ryan - no worries, brother. Went ahead and fixed the two typos (where ACTarray(x).WP = w I changed them to ACTarray(x).WP = WP), and declared the missing variables so I could push the hotfix. Version was bumped to 3.1.4 (in order for the update to be recognized in the field). Might want to run a git fetch to synchronize changes locally and import to VBE.

**Comment by ryanbeard82** [comment]
That doesn’t sound right. I’ll dig in later.

Respectfully,

Ryan Beard


[cid:8757CB1A-2705-47EE-9DF4-A6E33162E261@attlocal.net]


Tel: (256) 694-2745<tel:(256)%20694-2745>
Email: RyanBeard@ClearPlanConsulting.com<mailto:ryanbeard@clearplanconsulting.com>
Website: ClearPlanConsulting.com<http://www.clearplanconsulting.com/>


On Jun 24, 2019, at 11:58 AM, Aron Gahagan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey Ryan - no worries, brother. Went ahead and fixed the two typos (where ACTarray(x).WP = w I changed them to ACTarray(x).WP = WP), and declared the missing variables so I could push the hotfix. Version was bumped to 3.1.4 (in order for the update to be recognized in the field). Might want to run a git fetch to synchronize changes locally and import to VBE.

**Comment by AronGahagan** [comment]
OK will leave the issue open.
