### ISSUE TITLE
cptCriticalPath - error setting Task.TaskDependencies object

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#74]
Hey @ryanbeard82 would you mind taking a look at this for me?

## Problem:
User T Lake reports the following line of code is tripping an error in Microsoft Project 2010:

```visual-basic
141     'Store dependencies of user selected task
142     Set tdps = t.TaskDependencies
```
On the tested task, `Task.TaskDepencies.Count = 2` - one to the selected task (one predecessor) and one from the selected task (one successor). I took a screenshot but OneDrive stopped automatically saving them for me, for some reason, and it got overwritten.

[Edit: Forgot to mention, the variable appears to be correctly declared:
```visual-basic
39     Dim tdps As TaskDependencies
```
[/Edit]

## Solution
    how should this issue be addressed?

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout `develop` and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] reset BLN\_TRAP\_ERRORS
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `issueXX`
- [ ] merge `topic` into `develop` and push
- [ ] if hotfix: merge `develop` into `master` and push
- [ ] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by ryanbeard82** [comment]
Thanks .Will reach out to Tom. Will be close to impossible to debug without a copy of the file or a version of MSP 2010, but we'll see what we can do.

On Nov 18, 2019, at 4:22 PM, Aron Gahagan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @ryanbeard82<https://github.com/ryanbeard82> would you mind taking a look at this for me?

Problem:

User T Lake reports the following line of code is tripping an error in Microsoft Project 2010:

141     'Store dependencies of user selected task
142     Set tdps = t.TaskDependencies

On the tested task, Task.TaskDepencies.Count = 2 - one to the selected task (one predecessor) and one from the selected task (one successor). I took a screenshot but OneDrive stopped automatically saving them for me, for some reason, and it got overwritten.

Solution

how should this issue be addressed?


Todo:

  *    assign this issue
  *    label the issue for enhancement or bug
  *    label the issue with codemodule (so fixes can be aggregated and hotfixed together)
  *    checkout develop and create topic branch
  *    design, code and test
  *    update codemodule <cpt_version>x.y.z</cpt_version>
  *    reset BLN_TRAP_ERRORS
  *    update CurrentVersions.xml manually
  *    commit changes prefix comment with issueXX
  *    merge topic into develop and push
  *    if hotfix: merge develop into master and push
  *    if feature: wait for release, do not merge into master
  *    delete topic branch

**Comment by AronGahagan** [comment]
This issue appears to have been a fluke, resolved itself, or has otherwise dropped off of the radar. Closing it as OBE / `wontfix`.
